version: "3.7"
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - 9091:9091 # Unsecured HTTP Web Port
    environment:
      NIFI_WEB_HTTP_PORT: 9091
      HADOOP_NODE: datanode
      HADOOP_DATANODE_UI_PORT: 9865
    volumes:
      - "./nifi:/nifi:rw"
      #- "/opt/nifi/nifi-current/randomUser:/nifi/randomUser:rw"
    expose:
      - 9091
    networks:
      spark_net:
        ipv4_address: 172.28.1.7
    extra_hosts:
      - "kafka:172.28.1.9"
      - "zookeeper:172.28.1.8"
      - "db:172.28.1.10"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      spark_net:
        ipv4_address: 172.28.1.8
    extra_hosts:
      - "nifi:172.28.1.7"
      - "kafka:172.28.1.9"
   
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      spark_net:
        ipv4_address: 172.28.1.9
    extra_hosts:
      - "nifi:172.28.1.7"
      - "zookeeper:172.28.1.8"
      - "db:172.28.1.10"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      spark_net:
        ipv4_address: 172.28.1.10
    extra_hosts:
      - "nifi:172.28.1.7"
      - "kafka:172.28.1.9"
      
  cassandra:
     image: cassandra:latest
     container_name: cassandra
     ports:
        - "9042:9042"
     environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
     restart: always
     #volumes:
     #   - ./out/cassandra_data:/var/lib/cassandra
     networks:
      spark_net:
        ipv4_address: 172.28.1.11
     extra_hosts:
      - "nifi:172.28.1.7"
      - "kafka:172.28.1.9"


      
networks:
  spark_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
